name: Check

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  check:
    name: Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false
      - name: Install Nix
        uses: cachix/install-nix-action@13d8dd58da0234aa297dedd986986ccb8e7f3e24 # v31.11.1
      - name: Cache Nix store
        uses: nix-community/cache-nix-action@7df957e333c1e5da7721f60227dbba6d06080569 # v7.0.2
        with:
          primary-key: nix-${{ runner.os }}-${{ hashFiles('**/*.nix', '**/flake.lock') }}
          restore-prefixes-first-match: nix-${{ runner.os }}-
      - name: Load dev tools
        uses: tacbooon/nix-devshell-action@3a458f492717032fac03692cae6157662bbac49e # v1.1.0
      - name: Run flake check
        run: nix flake check --all-systems
      - name: Run nixfmt check
        run: git ls-files -z '*.nix' | xargs -0 nixfmt --check
      - name: Run actionlint check
        run: |
          echo "::add-matcher::.github/actionlint-matcher.json"
          actionlint -color
      - name: Run zizmor check
        run: zizmor . --persona auditor
        env:
          GH_TOKEN: ${{ github.token }}
      - name: Run shellcheck
        run: shellcheck install.sh
